version: '3.8'

services:
  uptime-kuma:
    build:
      context: ../.
      dockerfile: docker/dockerfile
    volumes:
      #- ./data:/app/data
      - ../server:/app/server
      - ../db:/app/db
    ports:
      - "3001:3001"  # <Host Port>:<Container Port>
      - "3307:3306"

